---
name: CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make openssl python3 python3-poetry
          poetry install --no-ansi
      - name: Verify ruleset signature
        run: |
          make verify
  lint:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make python3 python3-poetry
          poetry install --no-ansi
      - name: Run all linters
        run: |
            make lint

  build:
    name: Build
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
    with:
      context: "."
      containerfile: docker/Dockerfile
