---
name: CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-24.04
    container: debian:bookworm
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make openssl python3 python3-poetry
          poetry install --no-ansi
      - name: Verify ruleset signature
        run: |
          make verify
  lint:
    runs-on: ubuntu-24.04
    container: debian:bookworm
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make python3 python3-poetry
          poetry install --no-ansi
      - name: Check code formatting via black
        run: |
            make check-black
