---
name: Publish

on:
  push:
    branches: ["main", "staging"]

env:
  DEFAULT_BRANCH: main

jobs:
  build:
    name: Build
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
      packages: write
    with:
      context: "."
      containerfile: docker/Dockerfile
      registry: ghcr.io/freedomofpress/securedrop-https-everywhere-ruleset
      add-branch-tags: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  notify:
    uses: freedomofpress/actionslib/.github/workflows/update-k8s-trigger.yaml@main
    needs:
    - build
    if: ${{ needs.build.result == 'success' }}
    permissions:
      contents: read
      actions: read
      pull-requests: read
    with:
      trigger: https-everywhere/${{ github.ref_name }}
      sha: ${{ github.sha }}
    secrets:
      local-token: ${{ secrets.GITHUB_TOKEN }}
      k8s-configs-token: ${{ secrets.K8S_CONFIGS_GITHUB_TOKEN }}
